version: "3"
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    restart: always
    environment:
      TZ: Asia/Shanghai
    networks:
      - default

  php72:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP72_VERSION}
        PHP_XDEBUG: ${PHP72_XDEBUG}
        PHP_SWOOLE: ${PHP72_SWOOLE}
        PHP_REDIS: ${PHP72_REDIS}
        REPLACE_SOURCE_LIST: ${REPLACE_SOURCE_LIST}
    container_name: php72
    environment:
      # 设置时区，xdebug只能通过环境变量方式设置，在容器配置文件中设置无效
      TZ: Asia/Shanghai
      ENABLE_XDEBUG: 1 
      XDEBUG_CONFIG: remote_host=host.docker.internal
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP72_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP72_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  php56:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP56_VERSION}
        PHP_XDEBUG: ${PHP56_XDEBUG}
        PHP_SWOOLE: ${PHP56_SWOOLE}
        PHP_REDIS: ${PHP56_REDIS}
        REPLACE_SOURCE_LIST: ${REPLACE_SOURCE_LIST}
    container_name: php56
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP56_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP56_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  php54:
    build:
      context: .
      args:
        PHP_VERSION: ${PHP54_VERSION}
        PHP_XDEBUG: ${PHP54_XDEBUG}
        PHP_SWOOLE: ${PHP54_SWOOLE}
        PHP_REDIS: ${PHP54_REDIS}
        REPLACE_SOURCE_LIST: ${REPLACE_SOURCE_LIST}
    container_name: php54
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${PHP54_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP54_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  redis:
    image: redis:${REDIS_VERSION}
    restart: always
    networks:
      - default
    ports:
      - "${REDIS_HOST_PORT}:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "${PHPMYADMIN_HOST_PORT}:80"
    networks:
      - default
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    ports:
      - "${REDISMYADMIN_HOST_PORT}:80"
    networks:
      - default
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379

networks:
  default:
    external:
      name: my-bridge
